services:
  ecommerce:
    image: superutopios/ecommercefinal
    ports:
      - "8080:80"
    environment:
      - PS_DB_SERVER=db
      - PS_DB_NAME=ecommerce
      - PS_DB_USER=root
      - PS_DB_PASS=admin
    depends_on:
      - db
    
     

  db:
    image: superutopios/mysqlfinal
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ecommerce