services:
  ecommerce:
    image: klouss/ecommerce
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - PS_DB_SERVER=db
      - PS_DB_NAME=ecommerce
      - PS_DB_USER=root
      - PS_DB_PASS=/run/secrets/ps_db_pass
    secrets:
      - ps_db_pass
    depends_on:
      - db
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
  db:
    image: klouss/mysqlfinal
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ecommerce
    cap_drop:
      - ALL
    cap_add:
      - SYS_RESOURCE
secrets:
  ps_db_pass:
    external: true